### ISSUE TITLE
Modal: remove `visible` in favor of checking slot contents

### ISSUE THREAD

**Issue by fadeev** [tendermint/ui#100]
Right now there is a `visible` prop on `Modal` component that toggles visibility of the modal. Typically, modal is visible if there are contents inside, so instead of passing a boolean to `visible`, we can check `this.$slots.default`, but naive implementation of this is glitchy.

**Comment by nylira** [comment]
Isn't there times when you want to hide the modal without removing the content? Let's say the user wants to temporary hide the modal to do something in the main app screen first, or, in the case of a warning modal or loading modal, an event from the app toggles `visible` without any user action.

**Comment by fadeev** [comment]
These are valid cases, I agree.
