### ISSUE TITLE
fix test warnings caused by setProps

### ISSUE THREAD

**Issue by okwme** [tendermint/ui#27]

**Comment by faboweb** [comment]
What's the issue? Or are you already working on it and this is just a placeholder issue?

**Comment by okwme** [comment]
has to do with updating props in the tests, this is interpreted as overwriting a prop within the component. Happens with following tests:
 * tests/unit/TmFormMsg.spec.js
 * tests/unit/TmLiTransaction.spec.js
 * tests/unit/TmListItem.spec.js
 * tests/unit/TmTextMarkdown.spec.js

**Comment by okwme** [comment]
@faboweb might be we have to wait for an update to the vue test suite. just annoying to see red warnings when tests are passing and didn't want to forget to check up on it at a later date

**Comment by faboweb** [comment]
Ok with me. (See what I did there ;-D)
Small note: It is always helpful to provide a little context to not forget what the issue was about. (But I also forget often enough :/)

Red warnings? Shouldn't warnings fail the tests?

**Comment by okwme** [comment]
no totally, i hit submit too soon and was writing the followup post as i collected the misbehaving tests.
apparently warnings pass as they're just vue warnings:
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "type"
```
it's an open issue here: https://github.com/vuejs/vue-test-utils/issues/631

**Comment by faboweb** [comment]
In Voyager I created this strange script to fail tests that `console.warn`: https://github.com/cosmos/voyager/blob/develop/test/unit/helpers/console_error_throw.js

**Comment by okwme** [comment]
would be good to include once the warnings problem is squashed 🐞

**Comment by okwme** [comment]
supposed to be fixed w this update but i'm still seeing the error
https://github.com/vuejs/vue-test-utils/issues/631#event-1746102543

**Comment by lovincyrus** [comment]
Closed because of https://github.com/tendermint/ui/pull/95
