### ISSUE TITLE
tm-form-group

### ISSUE THREAD

**Issue by jolesbi** [tendermint/ui#29]
the variable `txt` is not working in the browser - "invalid property value" - it's appearing as a string not a hex code or a color.

```
.tm-form-group__label {
    display: block;
    line-height: 2rem;
    color: txt;
}
```

also, looks like these should be left aligned.

<img width="913" alt="screen shot 2018-07-12 at 10 20 47 pm" src="https://user-images.githubusercontent.com/6021933/42669105-db79e588-8621-11e8-8804-e9538fd47493.png">

**Comment by nylira** [comment]
I believe I fixed it in the 0.2.12 release. Can you try and see @jolesbi ?
